apiVersion: v1
kind: ServiceAccount
metadata:
  name: commerce-user
  namespace: commerce
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: commerce-order
  namespace: commerce
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: commerce-payment
  namespace: commerce
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: commerce-worker
  namespace: commerce
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: commerce-migrator
  namespace: commerce
automountServiceAccountToken: false
