// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: identity/v1/identity.proto

package identityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrincipalRole int32

const (
	PrincipalRole_PRINCIPAL_ROLE_UNSPECIFIED PrincipalRole = 0
	PrincipalRole_PRINCIPAL_ROLE_CUSTOMER    PrincipalRole = 1
	PrincipalRole_PRINCIPAL_ROLE_ADMIN       PrincipalRole = 2
)

// Enum value maps for PrincipalRole.
var (
	PrincipalRole_name = map[int32]string{
		0: "PRINCIPAL_ROLE_UNSPECIFIED",
		1: "PRINCIPAL_ROLE_CUSTOMER",
		2: "PRINCIPAL_ROLE_ADMIN",
	}
	PrincipalRole_value = map[string]int32{
		"PRINCIPAL_ROLE_UNSPECIFIED": 0,
		"PRINCIPAL_ROLE_CUSTOMER":    1,
		"PRINCIPAL_ROLE_ADMIN":       2,
	}
)

func (x PrincipalRole) Enum() *PrincipalRole {
	p := new(PrincipalRole)
	*p = x
	return p
}

func (x PrincipalRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrincipalRole) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_v1_identity_proto_enumTypes[0].Descriptor()
}

func (PrincipalRole) Type() protoreflect.EnumType {
	return &file_identity_v1_identity_proto_enumTypes[0]
}

func (x PrincipalRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrincipalRole.Descriptor instead.
func (PrincipalRole) EnumDescriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

type ValidateAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccessTokenRequest) Reset() {
	*x = ValidateAccessTokenRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessTokenRequest) ProtoMessage() {}

func (x *ValidateAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateAccessTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ValidateAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          PrincipalRole          `protobuf:"varint,2,opt,name=role,proto3,enum=identity.v1.PrincipalRole" json:"role,omitempty"`
	TokenId       string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccessTokenResponse) Reset() {
	*x = ValidateAccessTokenResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessTokenResponse) ProtoMessage() {}

func (x *ValidateAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateAccessTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateAccessTokenResponse) GetRole() PrincipalRole {
	if x != nil {
		return x.Role
	}
	return PrincipalRole_PRINCIPAL_ROLE_UNSPECIFIED
}

func (x *ValidateAccessTokenResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

var File_identity_v1_identity_proto protoreflect.FileDescriptor

const file_identity_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x1aidentity/v1/identity.proto\x12\videntity.v1\"?\n" +
	"\x1aValidateAccessTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\x81\x01\n" +
	"\x1bValidateAccessTokenResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1a.identity.v1.PrincipalRoleR\x04role\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId*f\n" +
	"\rPrincipalRole\x12\x1e\n" +
	"\x1aPRINCIPAL_ROLE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PRINCIPAL_ROLE_CUSTOMER\x10\x01\x12\x18\n" +
	"\x14PRINCIPAL_ROLE_ADMIN\x10\x022{\n" +
	"\x0fIdentityService\x12h\n" +
	"\x13ValidateAccessToken\x12'.identity.v1.ValidateAccessTokenRequest\x1a(.identity.v1.ValidateAccessTokenResponseBZZXgithub.com/assumeengagetry/distributed-commerce/internal/genproto/identity/v1;identityv1b\x06proto3"

var (
	file_identity_v1_identity_proto_rawDescOnce sync.Once
	file_identity_v1_identity_proto_rawDescData []byte
)

func file_identity_v1_identity_proto_rawDescGZIP() []byte {
	file_identity_v1_identity_proto_rawDescOnce.Do(func() {
		file_identity_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_identity_proto_rawDesc), len(file_identity_v1_identity_proto_rawDesc)))
	})
	return file_identity_v1_identity_proto_rawDescData
}

var file_identity_v1_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_identity_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_identity_v1_identity_proto_goTypes = []any{
	(PrincipalRole)(0),                  // 0: identity.v1.PrincipalRole
	(*ValidateAccessTokenRequest)(nil),  // 1: identity.v1.ValidateAccessTokenRequest
	(*ValidateAccessTokenResponse)(nil), // 2: identity.v1.ValidateAccessTokenResponse
}
var file_identity_v1_identity_proto_depIdxs = []int32{
	0, // 0: identity.v1.ValidateAccessTokenResponse.role:type_name -> identity.v1.PrincipalRole
	1, // 1: identity.v1.IdentityService.ValidateAccessToken:input_type -> identity.v1.ValidateAccessTokenRequest
	2, // 2: identity.v1.IdentityService.ValidateAccessToken:output_type -> identity.v1.ValidateAccessTokenResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_identity_v1_identity_proto_init() }
func file_identity_v1_identity_proto_init() {
	if File_identity_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_identity_proto_rawDesc), len(file_identity_v1_identity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_v1_identity_proto_goTypes,
		DependencyIndexes: file_identity_v1_identity_proto_depIdxs,
		EnumInfos:         file_identity_v1_identity_proto_enumTypes,
		MessageInfos:      file_identity_v1_identity_proto_msgTypes,
	}.Build()
	File_identity_v1_identity_proto = out.File
	file_identity_v1_identity_proto_goTypes = nil
	file_identity_v1_identity_proto_depIdxs = nil
}
