package order

import "errors"

var (
	ErrInvalidActor             = errors.New("invalid actor")
	ErrForbidden                = errors.New("permission denied")
	ErrAccountDisabled          = errors.New("account is disabled")
	ErrInvalidSKU               = errors.New("SKU must be 3 to 64 uppercase letters, numbers, dots, underscores, or hyphens")
	ErrInvalidProductName       = errors.New("product name must be between 1 and 200 characters")
	ErrInvalidDescription       = errors.New("product description must not exceed 2000 characters")
	ErrInvalidPrice             = errors.New("price amount is outside the supported range")
	ErrInvalidCurrency          = errors.New("only USD currency is supported")
	ErrInvalidProductStatus     = errors.New("product status must be active or inactive")
	ErrInvalidInitialQuantity   = errors.New("initial inventory quantity is outside the supported range")
	ErrEmptyProductUpdate       = errors.New("at least one product field must be updated")
	ErrInvalidExpectedVersion   = errors.New("expected version must be positive")
	ErrInvalidInventoryDelta    = errors.New("inventory delta must be non-zero and within the supported range")
	ErrInvalidPage              = errors.New("page limit or cursor is invalid")
	ErrInvalidOrderItems        = errors.New("an order must contain between 1 and 50 unique items")
	ErrInvalidItemQuantity      = errors.New("order item quantity is outside the supported range")
	ErrIdempotencyKeyRequired   = errors.New("Idempotency-Key header is required")
	ErrInvalidIdempotencyKey    = errors.New("Idempotency-Key header is invalid")
	ErrIdempotencyConflict      = errors.New("idempotency key was used for a different request")
	ErrIdempotencyInProgress    = errors.New("idempotent operation is still in progress")
	ErrOperationOutcomeUnknown  = errors.New("operation outcome is unknown")
	ErrProductNotFound          = errors.New("product not found")
	ErrSKUAlreadyExists         = errors.New("SKU already exists")
	ErrProductVersionConflict   = errors.New("product version conflict")
	ErrInventoryVersionConflict = errors.New("inventory version conflict")
	ErrInventoryOutOfRange      = errors.New("inventory adjustment would exceed supported bounds")
	ErrProductUnavailable       = errors.New("product is unavailable")
	ErrProductChanged           = errors.New("product changed")
	ErrInsufficientInventory    = errors.New("insufficient inventory")
	ErrCurrencyMismatch         = errors.New("product currency does not match the customer account")
	ErrOrderAmountTooLarge      = errors.New("order amount is too large")
	ErrOrderNotFound            = errors.New("order not found")
	ErrTemporarilyUnavailable   = errors.New("service temporarily unavailable")
)
