// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRefreshToken = `-- name: ConsumeRefreshToken :execrows
UPDATE refresh_tokens
SET consumed_at = $2
WHERE id = $1
  AND consumed_at IS NULL
`

type ConsumeRefreshTokenParams struct {
	ID         uuid.UUID          `json:"id"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

func (q *Queries) ConsumeRefreshToken(ctx context.Context, arg ConsumeRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeRefreshToken, arg.ID, arg.ConsumedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (
    id,
    user_id,
    expires_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $4
)
RETURNING id, user_id, expires_at, revoked_at, created_at, updated_at
`

type CreateAuthSessionParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    id,
    session_id,
    token_hash,
    created_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, session_id, token_hash, created_at, consumed_at
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"session_id"`
	TokenHash []byte    `json:"token_hash"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.SessionID,
		arg.TokenHash,
		arg.CreatedAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ConsumedAt,
	)
	return i, err
}

const deleteExpiredAuthSessions = `-- name: DeleteExpiredAuthSessions :execrows
DELETE FROM auth_sessions AS target
WHERE target.id IN (
    SELECT expired.id
    FROM auth_sessions AS expired
    WHERE expired.expires_at <= $1
    ORDER BY expired.expires_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
`

type DeleteExpiredAuthSessionsParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) DeleteExpiredAuthSessions(ctx context.Context, arg DeleteExpiredAuthSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthSessions, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshTokenStateForUpdate = `-- name: GetRefreshTokenStateForUpdate :one
SELECT
    rt.id AS refresh_token_id,
    rt.token_hash,
    rt.created_at AS refresh_created_at,
    rt.consumed_at,
    s.id AS session_id,
    s.expires_at AS session_expires_at,
    s.revoked_at AS session_revoked_at,
    u.id AS user_id,
    u.email,
    u.display_name,
    u.role,
    u.status,
    u.created_at AS user_created_at,
    u.updated_at AS user_updated_at,
    a.id AS account_id,
    a.currency,
    a.balance,
    a.created_at AS account_created_at,
    a.updated_at AS account_updated_at
FROM refresh_tokens AS rt
JOIN auth_sessions AS s ON s.id = rt.session_id
JOIN users AS u ON u.id = s.user_id
JOIN accounts AS a ON a.user_id = u.id
WHERE rt.id = $1
FOR UPDATE OF s, rt
`

type GetRefreshTokenStateForUpdateRow struct {
	RefreshTokenID   uuid.UUID          `json:"refresh_token_id"`
	TokenHash        []byte             `json:"token_hash"`
	RefreshCreatedAt time.Time          `json:"refresh_created_at"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
	SessionID        uuid.UUID          `json:"session_id"`
	SessionExpiresAt time.Time          `json:"session_expires_at"`
	SessionRevokedAt pgtype.Timestamptz `json:"session_revoked_at"`
	UserID           uuid.UUID          `json:"user_id"`
	Email            string             `json:"email"`
	DisplayName      string             `json:"display_name"`
	Role             string             `json:"role"`
	Status           string             `json:"status"`
	UserCreatedAt    time.Time          `json:"user_created_at"`
	UserUpdatedAt    time.Time          `json:"user_updated_at"`
	AccountID        uuid.UUID          `json:"account_id"`
	Currency         string             `json:"currency"`
	Balance          int64              `json:"balance"`
	AccountCreatedAt time.Time          `json:"account_created_at"`
	AccountUpdatedAt time.Time          `json:"account_updated_at"`
}

func (q *Queries) GetRefreshTokenStateForUpdate(ctx context.Context, id uuid.UUID) (GetRefreshTokenStateForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenStateForUpdate, id)
	var i GetRefreshTokenStateForUpdateRow
	err := row.Scan(
		&i.RefreshTokenID,
		&i.TokenHash,
		&i.RefreshCreatedAt,
		&i.ConsumedAt,
		&i.SessionID,
		&i.SessionExpiresAt,
		&i.SessionRevokedAt,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
		&i.AccountID,
		&i.Currency,
		&i.Balance,
		&i.AccountCreatedAt,
		&i.AccountUpdatedAt,
	)
	return i, err
}

const revokeAuthSession = `-- name: RevokeAuthSession :exec
UPDATE auth_sessions
SET revoked_at = COALESCE(revoked_at, $2),
    updated_at = $2
WHERE id = $1
`

type RevokeAuthSessionParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) error {
	_, err := q.db.Exec(ctx, revokeAuthSession, arg.ID, arg.UpdatedAt)
	return err
}
