// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package db

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :one
SELECT CASE
    WHEN to_regclass('public.users') IS NOT NULL
    AND to_regclass('public.accounts') IS NOT NULL
    AND to_regclass('public.auth_sessions') IS NOT NULL
    AND to_regclass('public.refresh_tokens') IS NOT NULL
    THEN 1::integer
    ELSE 0::integer
END
`

func (q *Queries) HealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const orderHealthCheck = `-- name: OrderHealthCheck :one
SELECT CASE
    WHEN to_regclass('public.users') IS NOT NULL
    AND to_regclass('public.accounts') IS NOT NULL
    AND to_regclass('public.products') IS NOT NULL
    AND to_regclass('public.inventories') IS NOT NULL
    AND to_regclass('public.orders') IS NOT NULL
    AND to_regclass('public.order_items') IS NOT NULL
    THEN 1::integer
    ELSE 0::integer
END
`

func (q *Queries) OrderHealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, orderHealthCheck)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
