// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :one
UPDATE idempotency_keys
SET state = 'completed',
    response_status = $6,
    completed_at = clock_timestamp()
WHERE actor_id = $1
  AND operation = $2
  AND key_hash = $3
  AND request_hash = $4
  AND resource_id = $5
  AND state = 'reserved'
RETURNING actor_id, operation, key_hash, request_hash, resource_id,
          state, response_status, created_at, completed_at
`

type CompleteIdempotencyKeyParams struct {
	ActorID        uuid.UUID   `json:"actor_id"`
	Operation      string      `json:"operation"`
	KeyHash        []byte      `json:"key_hash"`
	RequestHash    []byte      `json:"request_hash"`
	ResourceID     uuid.UUID   `json:"resource_id"`
	ResponseStatus pgtype.Int2 `json:"response_status"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, completeIdempotencyKey,
		arg.ActorID,
		arg.Operation,
		arg.KeyHash,
		arg.RequestHash,
		arg.ResourceID,
		arg.ResponseStatus,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ActorID,
		&i.Operation,
		&i.KeyHash,
		&i.RequestHash,
		&i.ResourceID,
		&i.State,
		&i.ResponseStatus,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT actor_id, operation, key_hash, request_hash, resource_id,
       state, response_status, created_at, completed_at
FROM idempotency_keys
WHERE actor_id = $1 AND operation = $2 AND key_hash = $3
`

type GetIdempotencyKeyParams struct {
	ActorID   uuid.UUID `json:"actor_id"`
	Operation string    `json:"operation"`
	KeyHash   []byte    `json:"key_hash"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.ActorID, arg.Operation, arg.KeyHash)
	var i IdempotencyKey
	err := row.Scan(
		&i.ActorID,
		&i.Operation,
		&i.KeyHash,
		&i.RequestHash,
		&i.ResourceID,
		&i.State,
		&i.ResponseStatus,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getIdempotencyKeyForUpdate = `-- name: GetIdempotencyKeyForUpdate :one
SELECT actor_id, operation, key_hash, request_hash, resource_id,
       state, response_status, created_at, completed_at
FROM idempotency_keys
WHERE actor_id = $1 AND operation = $2 AND key_hash = $3
FOR UPDATE
`

type GetIdempotencyKeyForUpdateParams struct {
	ActorID   uuid.UUID `json:"actor_id"`
	Operation string    `json:"operation"`
	KeyHash   []byte    `json:"key_hash"`
}

func (q *Queries) GetIdempotencyKeyForUpdate(ctx context.Context, arg GetIdempotencyKeyForUpdateParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKeyForUpdate, arg.ActorID, arg.Operation, arg.KeyHash)
	var i IdempotencyKey
	err := row.Scan(
		&i.ActorID,
		&i.Operation,
		&i.KeyHash,
		&i.RequestHash,
		&i.ResourceID,
		&i.State,
		&i.ResponseStatus,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const reserveIdempotencyKey = `-- name: ReserveIdempotencyKey :one
INSERT INTO idempotency_keys (
    actor_id, operation, key_hash, request_hash, resource_id,
    state, response_status, created_at, completed_at
) VALUES (
    $1, $2, $3, $4, $5, 'reserved', NULL, clock_timestamp(), NULL
)
ON CONFLICT (actor_id, operation, key_hash) DO NOTHING
RETURNING actor_id, operation, key_hash, request_hash, resource_id,
          state, response_status, created_at, completed_at
`

type ReserveIdempotencyKeyParams struct {
	ActorID     uuid.UUID `json:"actor_id"`
	Operation   string    `json:"operation"`
	KeyHash     []byte    `json:"key_hash"`
	RequestHash []byte    `json:"request_hash"`
	ResourceID  uuid.UUID `json:"resource_id"`
}

func (q *Queries) ReserveIdempotencyKey(ctx context.Context, arg ReserveIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, reserveIdempotencyKey,
		arg.ActorID,
		arg.Operation,
		arg.KeyHash,
		arg.RequestHash,
		arg.ResourceID,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ActorID,
		&i.Operation,
		&i.KeyHash,
		&i.RequestHash,
		&i.ResourceID,
		&i.State,
		&i.ResponseStatus,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}
