// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	Currency       string    `json:"currency"`
	Balance        int64     `json:"balance"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	BalanceVersion int64     `json:"balance_version"`
}

type AccountBalanceEntry struct {
	AccountID      uuid.UUID `json:"account_id"`
	UserID         uuid.UUID `json:"user_id"`
	Currency       string    `json:"currency"`
	BalanceVersion int64     `json:"balance_version"`
	BalanceBefore  int64     `json:"balance_before"`
	BalanceAfter   int64     `json:"balance_after"`
	DebitAmount    int64     `json:"debit_amount"`
	CreatedAt      time.Time `json:"created_at"`
}

type AuthSession struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt time.Time          `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
}

type IdempotencyKey struct {
	ActorID        uuid.UUID          `json:"actor_id"`
	Operation      string             `json:"operation"`
	KeyHash        []byte             `json:"key_hash"`
	RequestHash    []byte             `json:"request_hash"`
	ResourceID     uuid.UUID          `json:"resource_id"`
	State          string             `json:"state"`
	ResponseStatus pgtype.Int2        `json:"response_status"`
	CreatedAt      time.Time          `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type Inventory struct {
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int64     `json:"quantity"`
	Version   int64     `json:"version"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Order struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Status      string    `json:"status"`
	Currency    string    `json:"currency"`
	TotalAmount int64     `json:"total_amount"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type OrderItem struct {
	ID              uuid.UUID `json:"id"`
	OrderID         uuid.UUID `json:"order_id"`
	ProductID       uuid.UUID `json:"product_id"`
	ProductSku      string    `json:"product_sku"`
	ProductName     string    `json:"product_name"`
	ProductVersion  int64     `json:"product_version"`
	Quantity        int64     `json:"quantity"`
	UnitPriceAmount int64     `json:"unit_price_amount"`
	LineAmount      int64     `json:"line_amount"`
	CreatedAt       time.Time `json:"created_at"`
}

type Payment struct {
	ID                    uuid.UUID `json:"id"`
	OrderID               uuid.UUID `json:"order_id"`
	UserID                uuid.UUID `json:"user_id"`
	AccountID             uuid.UUID `json:"account_id"`
	AccountBalanceVersion int64     `json:"account_balance_version"`
	Status                string    `json:"status"`
	Currency              string    `json:"currency"`
	Amount                int64     `json:"amount"`
	BalanceBefore         int64     `json:"balance_before"`
	BalanceAfter          int64     `json:"balance_after"`
	CreatedAt             time.Time `json:"created_at"`
}

type Product struct {
	ID          uuid.UUID `json:"id"`
	Sku         string    `json:"sku"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	PriceAmount int64     `json:"price_amount"`
	Currency    string    `json:"currency"`
	Status      string    `json:"status"`
	Version     int64     `json:"version"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type RefreshToken struct {
	ID         uuid.UUID          `json:"id"`
	SessionID  uuid.UUID          `json:"session_id"`
	TokenHash  []byte             `json:"token_hash"`
	CreatedAt  time.Time          `json:"created_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	DisplayName  string    `json:"display_name"`
	Role         string    `json:"role"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
