// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, user_id, status, currency, total_amount, created_at, updated_at)
VALUES ($1, $2, 'pending', $3, $4, $5, $5)
RETURNING id, user_id, status, currency, total_amount, created_at, updated_at
`

type CreateOrderParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Currency    string    `json:"currency"`
	TotalAmount int64     `json:"total_amount"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.Currency,
		arg.TotalAmount,
		arg.CreatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    id, order_id, product_id, product_sku, product_name, product_version,
    quantity, unit_price_amount, line_amount, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, order_id, product_id, product_sku, product_name, product_version,
          quantity, unit_price_amount, line_amount, created_at
`

type CreateOrderItemParams struct {
	ID              uuid.UUID `json:"id"`
	OrderID         uuid.UUID `json:"order_id"`
	ProductID       uuid.UUID `json:"product_id"`
	ProductSku      string    `json:"product_sku"`
	ProductName     string    `json:"product_name"`
	ProductVersion  int64     `json:"product_version"`
	Quantity        int64     `json:"quantity"`
	UnitPriceAmount int64     `json:"unit_price_amount"`
	LineAmount      int64     `json:"line_amount"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.ProductSku,
		arg.ProductName,
		arg.ProductVersion,
		arg.Quantity,
		arg.UnitPriceAmount,
		arg.LineAmount,
		arg.CreatedAt,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductSku,
		&i.ProductName,
		&i.ProductVersion,
		&i.Quantity,
		&i.UnitPriceAmount,
		&i.LineAmount,
		&i.CreatedAt,
	)
	return i, err
}

const deductInventoryForOrder = `-- name: DeductInventoryForOrder :one
UPDATE inventories
SET quantity = quantity - $2,
    version = version + 1,
    updated_at = $3
WHERE product_id = $1
  AND quantity >= $2
RETURNING product_id, quantity, version, created_at, updated_at
`

type DeductInventoryForOrderParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int64     `json:"quantity"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) DeductInventoryForOrder(ctx context.Context, arg DeductInventoryForOrderParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, deductInventoryForOrder, arg.ProductID, arg.Quantity, arg.UpdatedAt)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.Quantity,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommerceActorForShare = `-- name: GetCommerceActorForShare :one
SELECT u.id, u.role, u.status, a.currency
FROM users AS u
JOIN accounts AS a ON a.user_id = u.id
WHERE u.id = $1
FOR SHARE OF u, a
`

type GetCommerceActorForShareRow struct {
	ID       uuid.UUID `json:"id"`
	Role     string    `json:"role"`
	Status   string    `json:"status"`
	Currency string    `json:"currency"`
}

func (q *Queries) GetCommerceActorForShare(ctx context.Context, id uuid.UUID) (GetCommerceActorForShareRow, error) {
	row := q.db.QueryRow(ctx, getCommerceActorForShare, id)
	var i GetCommerceActorForShareRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Status,
		&i.Currency,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, status, currency, total_amount, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByIDAndUser = `-- name: GetOrderByIDAndUser :one
SELECT id, user_id, status, currency, total_amount, created_at, updated_at
FROM orders
WHERE id = $1 AND user_id = $2
`

type GetOrderByIDAndUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOrderByIDAndUser(ctx context.Context, arg GetOrderByIDAndUserParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIDAndUser, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductForOrder = `-- name: GetProductForOrder :one
SELECT id, sku, name, price_amount, currency, status, version
FROM products
WHERE id = $1
FOR SHARE
`

type GetProductForOrderRow struct {
	ID          uuid.UUID `json:"id"`
	Sku         string    `json:"sku"`
	Name        string    `json:"name"`
	PriceAmount int64     `json:"price_amount"`
	Currency    string    `json:"currency"`
	Status      string    `json:"status"`
	Version     int64     `json:"version"`
}

func (q *Queries) GetProductForOrder(ctx context.Context, id uuid.UUID) (GetProductForOrderRow, error) {
	row := q.db.QueryRow(ctx, getProductForOrder, id)
	var i GetProductForOrderRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.PriceAmount,
		&i.Currency,
		&i.Status,
		&i.Version,
	)
	return i, err
}

const listAllOrders = `-- name: ListAllOrders :many
SELECT id, user_id, status, currency, total_amount, created_at, updated_at
FROM orders
ORDER BY created_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListAllOrders(ctx context.Context, limit int32) ([]Order, error) {
	rows, err := q.db.Query(ctx, listAllOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Currency,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllOrdersAfter = `-- name: ListAllOrdersAfter :many
SELECT id, user_id, status, currency, total_amount, created_at, updated_at
FROM orders
WHERE (created_at, id) < (
    $1::timestamptz,
    $2::uuid
)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListAllOrdersAfterParams struct {
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	ResultLimit     int32     `json:"result_limit"`
}

func (q *Queries) ListAllOrdersAfter(ctx context.Context, arg ListAllOrdersAfterParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listAllOrdersAfter, arg.CursorCreatedAt, arg.CursorID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Currency,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT id, order_id, product_id, product_sku, product_name, product_version,
       quantity, unit_price_amount, line_amount, created_at
FROM order_items
WHERE order_id = $1
ORDER BY id
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductSku,
			&i.ProductName,
			&i.ProductVersion,
			&i.Quantity,
			&i.UnitPriceAmount,
			&i.LineAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrderIDs = `-- name: ListOrderItemsByOrderIDs :many
SELECT id, order_id, product_id, product_sku, product_name, product_version,
       quantity, unit_price_amount, line_amount, created_at
FROM order_items
WHERE order_id = ANY($1::uuid[])
ORDER BY order_id, id
`

func (q *Queries) ListOrderItemsByOrderIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductSku,
			&i.ProductName,
			&i.ProductVersion,
			&i.Quantity,
			&i.UnitPriceAmount,
			&i.LineAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, status, currency, total_amount, created_at, updated_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListOrdersByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Currency,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserAfter = `-- name: ListOrdersByUserAfter :many
SELECT id, user_id, status, currency, total_amount, created_at, updated_at
FROM orders
WHERE user_id = $1
  AND (created_at, id) < (
      $2::timestamptz,
      $3::uuid
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListOrdersByUserAfterParams struct {
	UserID          uuid.UUID `json:"user_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	ResultLimit     int32     `json:"result_limit"`
}

func (q *Queries) ListOrdersByUserAfter(ctx context.Context, arg ListOrdersByUserAfterParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUserAfter,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Currency,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
