// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    id, order_id, user_id, account_id, account_balance_version, status, currency, amount,
    balance_before, balance_after, created_at
) VALUES (
    $1, $2, $3, $4, $5, 'succeeded', $6, $7, $8, $9, $10
)
RETURNING id, order_id, user_id, account_id, account_balance_version, status, currency, amount,
          balance_before, balance_after, created_at
`

type CreatePaymentParams struct {
	ID                    uuid.UUID `json:"id"`
	OrderID               uuid.UUID `json:"order_id"`
	UserID                uuid.UUID `json:"user_id"`
	AccountID             uuid.UUID `json:"account_id"`
	AccountBalanceVersion int64     `json:"account_balance_version"`
	Currency              string    `json:"currency"`
	Amount                int64     `json:"amount"`
	BalanceBefore         int64     `json:"balance_before"`
	BalanceAfter          int64     `json:"balance_after"`
	CreatedAt             time.Time `json:"created_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.OrderID,
		arg.UserID,
		arg.AccountID,
		arg.AccountBalanceVersion,
		arg.Currency,
		arg.Amount,
		arg.BalanceBefore,
		arg.BalanceAfter,
		arg.CreatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.AccountID,
		&i.AccountBalanceVersion,
		&i.Status,
		&i.Currency,
		&i.Amount,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.CreatedAt,
	)
	return i, err
}

const debitAccountForPayment = `-- name: DebitAccountForPayment :one
UPDATE accounts
SET balance = balance - $1::bigint,
    updated_at = $2::timestamptz
WHERE id = $3::uuid
  AND user_id = $4::uuid
  AND currency = $5::text
  AND balance = $6::bigint
  AND balance >= $1::bigint
RETURNING id, user_id, currency, balance, balance_version, created_at, updated_at
`

type DebitAccountForPaymentParams struct {
	Amount          int64     `json:"amount"`
	UpdatedAt       time.Time `json:"updated_at"`
	AccountID       uuid.UUID `json:"account_id"`
	UserID          uuid.UUID `json:"user_id"`
	Currency        string    `json:"currency"`
	ExpectedBalance int64     `json:"expected_balance"`
}

type DebitAccountForPaymentRow struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	Currency       string    `json:"currency"`
	Balance        int64     `json:"balance"`
	BalanceVersion int64     `json:"balance_version"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) DebitAccountForPayment(ctx context.Context, arg DebitAccountForPaymentParams) (DebitAccountForPaymentRow, error) {
	row := q.db.QueryRow(ctx, debitAccountForPayment,
		arg.Amount,
		arg.UpdatedAt,
		arg.AccountID,
		arg.UserID,
		arg.Currency,
		arg.ExpectedBalance,
	)
	var i DebitAccountForPaymentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.BalanceVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountForPayment = `-- name: GetAccountForPayment :one
SELECT id, user_id, currency, balance, balance_version, created_at, updated_at
FROM accounts
WHERE user_id = $1
FOR UPDATE
`

type GetAccountForPaymentRow struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	Currency       string    `json:"currency"`
	Balance        int64     `json:"balance"`
	BalanceVersion int64     `json:"balance_version"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) GetAccountForPayment(ctx context.Context, userID uuid.UUID) (GetAccountForPaymentRow, error) {
	row := q.db.QueryRow(ctx, getAccountForPayment, userID)
	var i GetAccountForPaymentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.BalanceVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderForPayment = `-- name: GetOrderForPayment :one
SELECT id, user_id, status, currency, total_amount, created_at, updated_at
FROM orders
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type GetOrderForPaymentParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOrderForPayment(ctx context.Context, arg GetOrderForPaymentParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForPayment, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentActorForShare = `-- name: GetPaymentActorForShare :one
SELECT id, role, status
FROM users
WHERE id = $1
FOR SHARE
`

type GetPaymentActorForShareRow struct {
	ID     uuid.UUID `json:"id"`
	Role   string    `json:"role"`
	Status string    `json:"status"`
}

func (q *Queries) GetPaymentActorForShare(ctx context.Context, id uuid.UUID) (GetPaymentActorForShareRow, error) {
	row := q.db.QueryRow(ctx, getPaymentActorForShare, id)
	var i GetPaymentActorForShareRow
	err := row.Scan(&i.ID, &i.Role, &i.Status)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, order_id, user_id, account_id, account_balance_version, status, currency, amount,
       balance_before, balance_after, created_at
FROM payments
WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.AccountID,
		&i.AccountBalanceVersion,
		&i.Status,
		&i.Currency,
		&i.Amount,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByIDAndUser = `-- name: GetPaymentByIDAndUser :one
SELECT id, order_id, user_id, account_id, account_balance_version, status, currency, amount,
       balance_before, balance_after, created_at
FROM payments
WHERE id = $1 AND user_id = $2
`

type GetPaymentByIDAndUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPaymentByIDAndUser(ctx context.Context, arg GetPaymentByIDAndUserParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIDAndUser, arg.ID, arg.UserID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.AccountID,
		&i.AccountBalanceVersion,
		&i.Status,
		&i.Currency,
		&i.Amount,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.CreatedAt,
	)
	return i, err
}

const markOrderPaid = `-- name: MarkOrderPaid :one
UPDATE orders
SET status = 'paid', updated_at = $3
WHERE id = $1 AND user_id = $2 AND status = 'pending'
RETURNING id, user_id, status, currency, total_amount, created_at, updated_at
`

type MarkOrderPaidParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) MarkOrderPaid(ctx context.Context, arg MarkOrderPaidParams) (Order, error) {
	row := q.db.QueryRow(ctx, markOrderPaid, arg.ID, arg.UserID, arg.UpdatedAt)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
