// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventories (product_id, quantity, version, created_at, updated_at)
VALUES ($1, $2, 1, $3, $3)
RETURNING product_id, quantity, version, created_at, updated_at
`

type CreateInventoryParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int64     `json:"quantity"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventory, arg.ProductID, arg.Quantity, arg.CreatedAt)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.Quantity,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    id, sku, name, description, price_amount, currency, status, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 1, $8, $8
)
RETURNING id, sku, name, description, price_amount, currency, status, version, created_at, updated_at
`

type CreateProductParams struct {
	ID          uuid.UUID `json:"id"`
	Sku         string    `json:"sku"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	PriceAmount int64     `json:"price_amount"`
	Currency    string    `json:"currency"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.PriceAmount,
		arg.Currency,
		arg.Status,
		arg.CreatedAt,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.PriceAmount,
		&i.Currency,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveProductByID = `-- name: GetActiveProductByID :one
SELECT
    p.id, p.sku, p.name, p.description, p.price_amount, p.currency,
    p.status, p.version, p.created_at, p.updated_at,
    i.quantity, i.version AS inventory_version, i.updated_at AS inventory_updated_at
FROM products AS p
JOIN inventories AS i ON i.product_id = p.id
WHERE p.id = $1 AND p.status = 'active'
`

type GetActiveProductByIDRow struct {
	ID                 uuid.UUID `json:"id"`
	Sku                string    `json:"sku"`
	Name               string    `json:"name"`
	Description        string    `json:"description"`
	PriceAmount        int64     `json:"price_amount"`
	Currency           string    `json:"currency"`
	Status             string    `json:"status"`
	Version            int64     `json:"version"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	Quantity           int64     `json:"quantity"`
	InventoryVersion   int64     `json:"inventory_version"`
	InventoryUpdatedAt time.Time `json:"inventory_updated_at"`
}

func (q *Queries) GetActiveProductByID(ctx context.Context, id uuid.UUID) (GetActiveProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveProductByID, id)
	var i GetActiveProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.PriceAmount,
		&i.Currency,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Quantity,
		&i.InventoryVersion,
		&i.InventoryUpdatedAt,
	)
	return i, err
}

const getInventoryForUpdate = `-- name: GetInventoryForUpdate :one
SELECT
    i.product_id, i.quantity, i.version, i.created_at, i.updated_at,
    p.sku, p.name, p.status
FROM inventories AS i
JOIN products AS p ON p.id = i.product_id
WHERE i.product_id = $1
FOR UPDATE OF i
`

type GetInventoryForUpdateRow struct {
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int64     `json:"quantity"`
	Version   int64     `json:"version"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Sku       string    `json:"sku"`
	Name      string    `json:"name"`
	Status    string    `json:"status"`
}

func (q *Queries) GetInventoryForUpdate(ctx context.Context, productID uuid.UUID) (GetInventoryForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getInventoryForUpdate, productID)
	var i GetInventoryForUpdateRow
	err := row.Scan(
		&i.ProductID,
		&i.Quantity,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Sku,
		&i.Name,
		&i.Status,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    p.id, p.sku, p.name, p.description, p.price_amount, p.currency,
    p.status, p.version, p.created_at, p.updated_at,
    i.quantity, i.version AS inventory_version, i.updated_at AS inventory_updated_at
FROM products AS p
JOIN inventories AS i ON i.product_id = p.id
WHERE p.id = $1
`

type GetProductByIDRow struct {
	ID                 uuid.UUID `json:"id"`
	Sku                string    `json:"sku"`
	Name               string    `json:"name"`
	Description        string    `json:"description"`
	PriceAmount        int64     `json:"price_amount"`
	Currency           string    `json:"currency"`
	Status             string    `json:"status"`
	Version            int64     `json:"version"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	Quantity           int64     `json:"quantity"`
	InventoryVersion   int64     `json:"inventory_version"`
	InventoryUpdatedAt time.Time `json:"inventory_updated_at"`
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.PriceAmount,
		&i.Currency,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Quantity,
		&i.InventoryVersion,
		&i.InventoryUpdatedAt,
	)
	return i, err
}

const getProductForUpdate = `-- name: GetProductForUpdate :one
SELECT
    p.id, p.sku, p.name, p.description, p.price_amount, p.currency,
    p.status, p.version, p.created_at, p.updated_at
FROM products AS p
WHERE p.id = $1
FOR UPDATE OF p
`

func (q *Queries) GetProductForUpdate(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductForUpdate, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.PriceAmount,
		&i.Currency,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT
    p.id, p.sku, p.name, p.description, p.price_amount, p.currency,
    p.status, p.version, p.created_at, p.updated_at,
    i.quantity, i.version AS inventory_version, i.updated_at AS inventory_updated_at
FROM products AS p
JOIN inventories AS i ON i.product_id = p.id
WHERE p.status = 'active'
ORDER BY p.created_at DESC, p.id DESC
LIMIT $1
`

type ListActiveProductsRow struct {
	ID                 uuid.UUID `json:"id"`
	Sku                string    `json:"sku"`
	Name               string    `json:"name"`
	Description        string    `json:"description"`
	PriceAmount        int64     `json:"price_amount"`
	Currency           string    `json:"currency"`
	Status             string    `json:"status"`
	Version            int64     `json:"version"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	Quantity           int64     `json:"quantity"`
	InventoryVersion   int64     `json:"inventory_version"`
	InventoryUpdatedAt time.Time `json:"inventory_updated_at"`
}

func (q *Queries) ListActiveProducts(ctx context.Context, limit int32) ([]ListActiveProductsRow, error) {
	rows, err := q.db.Query(ctx, listActiveProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveProductsRow{}
	for rows.Next() {
		var i ListActiveProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.PriceAmount,
			&i.Currency,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Quantity,
			&i.InventoryVersion,
			&i.InventoryUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveProductsAfter = `-- name: ListActiveProductsAfter :many
SELECT
    p.id, p.sku, p.name, p.description, p.price_amount, p.currency,
    p.status, p.version, p.created_at, p.updated_at,
    i.quantity, i.version AS inventory_version, i.updated_at AS inventory_updated_at
FROM products AS p
JOIN inventories AS i ON i.product_id = p.id
WHERE p.status = 'active'
  AND (p.created_at, p.id) < (
      $1::timestamptz,
      $2::uuid
  )
ORDER BY p.created_at DESC, p.id DESC
LIMIT $3
`

type ListActiveProductsAfterParams struct {
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	ResultLimit     int32     `json:"result_limit"`
}

type ListActiveProductsAfterRow struct {
	ID                 uuid.UUID `json:"id"`
	Sku                string    `json:"sku"`
	Name               string    `json:"name"`
	Description        string    `json:"description"`
	PriceAmount        int64     `json:"price_amount"`
	Currency           string    `json:"currency"`
	Status             string    `json:"status"`
	Version            int64     `json:"version"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	Quantity           int64     `json:"quantity"`
	InventoryVersion   int64     `json:"inventory_version"`
	InventoryUpdatedAt time.Time `json:"inventory_updated_at"`
}

func (q *Queries) ListActiveProductsAfter(ctx context.Context, arg ListActiveProductsAfterParams) ([]ListActiveProductsAfterRow, error) {
	rows, err := q.db.Query(ctx, listActiveProductsAfter, arg.CursorCreatedAt, arg.CursorID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveProductsAfterRow{}
	for rows.Next() {
		var i ListActiveProductsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.PriceAmount,
			&i.Currency,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Quantity,
			&i.InventoryVersion,
			&i.InventoryUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventory = `-- name: ListInventory :many
SELECT
    p.id AS product_id, p.sku, p.name, p.status, p.created_at AS product_created_at,
    i.quantity, i.version, i.updated_at
FROM products AS p
JOIN inventories AS i ON i.product_id = p.id
ORDER BY p.created_at DESC, p.id DESC
LIMIT $1
`

type ListInventoryRow struct {
	ProductID        uuid.UUID `json:"product_id"`
	Sku              string    `json:"sku"`
	Name             string    `json:"name"`
	Status           string    `json:"status"`
	ProductCreatedAt time.Time `json:"product_created_at"`
	Quantity         int64     `json:"quantity"`
	Version          int64     `json:"version"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) ListInventory(ctx context.Context, limit int32) ([]ListInventoryRow, error) {
	rows, err := q.db.Query(ctx, listInventory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryRow{}
	for rows.Next() {
		var i ListInventoryRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.Status,
			&i.ProductCreatedAt,
			&i.Quantity,
			&i.Version,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryAfter = `-- name: ListInventoryAfter :many
SELECT
    p.id AS product_id, p.sku, p.name, p.status, p.created_at AS product_created_at,
    i.quantity, i.version, i.updated_at
FROM products AS p
JOIN inventories AS i ON i.product_id = p.id
WHERE (p.created_at, p.id) < (
    $1::timestamptz,
    $2::uuid
)
ORDER BY p.created_at DESC, p.id DESC
LIMIT $3
`

type ListInventoryAfterParams struct {
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	ResultLimit     int32     `json:"result_limit"`
}

type ListInventoryAfterRow struct {
	ProductID        uuid.UUID `json:"product_id"`
	Sku              string    `json:"sku"`
	Name             string    `json:"name"`
	Status           string    `json:"status"`
	ProductCreatedAt time.Time `json:"product_created_at"`
	Quantity         int64     `json:"quantity"`
	Version          int64     `json:"version"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) ListInventoryAfter(ctx context.Context, arg ListInventoryAfterParams) ([]ListInventoryAfterRow, error) {
	rows, err := q.db.Query(ctx, listInventoryAfter, arg.CursorCreatedAt, arg.CursorID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryAfterRow{}
	for rows.Next() {
		var i ListInventoryAfterRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.Status,
			&i.ProductCreatedAt,
			&i.Quantity,
			&i.Version,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventory = `-- name: UpdateInventory :one
UPDATE inventories
SET quantity = $2,
    version = version + 1,
    updated_at = $3
WHERE product_id = $1 AND version = $4
RETURNING product_id, quantity, version, created_at, updated_at
`

type UpdateInventoryParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int64     `json:"quantity"`
	UpdatedAt time.Time `json:"updated_at"`
	Version   int64     `json:"version"`
}

func (q *Queries) UpdateInventory(ctx context.Context, arg UpdateInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, updateInventory,
		arg.ProductID,
		arg.Quantity,
		arg.UpdatedAt,
		arg.Version,
	)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.Quantity,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2,
    description = $3,
    price_amount = $4,
    status = $5,
    version = version + 1,
    updated_at = $6
WHERE id = $1 AND version = $7
RETURNING id, sku, name, description, price_amount, currency, status, version, created_at, updated_at
`

type UpdateProductParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	PriceAmount int64     `json:"price_amount"`
	Status      string    `json:"status"`
	UpdatedAt   time.Time `json:"updated_at"`
	Version     int64     `json:"version"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceAmount,
		arg.Status,
		arg.UpdatedAt,
		arg.Version,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.PriceAmount,
		&i.Currency,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
