// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id,
    user_id,
    currency,
    balance,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, 0, $4, $4
)
RETURNING id, user_id, currency, balance, created_at, updated_at
`

type CreateAccountParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.UserID,
		arg.Currency,
		arg.CreatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    email,
    password_hash,
    display_name,
    role,
    status,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, 'active', $6, $6
)
RETURNING id, email, password_hash, display_name, role, status, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	DisplayName  string    `json:"display_name"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Role,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCredentialsByEmail = `-- name: GetUserCredentialsByEmail :one
SELECT
    u.id,
    u.email,
    u.password_hash,
    u.display_name,
    u.role,
    u.status,
    u.created_at,
    u.updated_at,
    a.id AS account_id,
    a.currency,
    a.balance,
    a.created_at AS account_created_at,
    a.updated_at AS account_updated_at
FROM users AS u
JOIN accounts AS a ON a.user_id = u.id
WHERE u.email = $1
`

type GetUserCredentialsByEmailRow struct {
	ID               uuid.UUID `json:"id"`
	Email            string    `json:"email"`
	PasswordHash     string    `json:"password_hash"`
	DisplayName      string    `json:"display_name"`
	Role             string    `json:"role"`
	Status           string    `json:"status"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	AccountID        uuid.UUID `json:"account_id"`
	Currency         string    `json:"currency"`
	Balance          int64     `json:"balance"`
	AccountCreatedAt time.Time `json:"account_created_at"`
	AccountUpdatedAt time.Time `json:"account_updated_at"`
}

func (q *Queries) GetUserCredentialsByEmail(ctx context.Context, email string) (GetUserCredentialsByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialsByEmail, email)
	var i GetUserCredentialsByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
		&i.Currency,
		&i.Balance,
		&i.AccountCreatedAt,
		&i.AccountUpdatedAt,
	)
	return i, err
}

const getUserProfileByID = `-- name: GetUserProfileByID :one
SELECT
    u.id,
    u.email,
    u.display_name,
    u.role,
    u.status,
    u.created_at,
    u.updated_at,
    a.id AS account_id,
    a.currency,
    a.balance,
    a.created_at AS account_created_at,
    a.updated_at AS account_updated_at
FROM users AS u
JOIN accounts AS a ON a.user_id = u.id
WHERE u.id = $1
`

type GetUserProfileByIDRow struct {
	ID               uuid.UUID `json:"id"`
	Email            string    `json:"email"`
	DisplayName      string    `json:"display_name"`
	Role             string    `json:"role"`
	Status           string    `json:"status"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	AccountID        uuid.UUID `json:"account_id"`
	Currency         string    `json:"currency"`
	Balance          int64     `json:"balance"`
	AccountCreatedAt time.Time `json:"account_created_at"`
	AccountUpdatedAt time.Time `json:"account_updated_at"`
}

func (q *Queries) GetUserProfileByID(ctx context.Context, id uuid.UUID) (GetUserProfileByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserProfileByID, id)
	var i GetUserProfileByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
		&i.Currency,
		&i.Balance,
		&i.AccountCreatedAt,
		&i.AccountUpdatedAt,
	)
	return i, err
}
